"""add_indexes_and_draft_version_unique

Revision ID: 1a6a93bbbcc9
Revises: 607cc55778da
Create Date: 2026-05-18 08:56:18.970859
"""

from alembic import op
import sqlalchemy as sa



revision = '1a6a93bbbcc9'
down_revision = '607cc55778da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drafts_project_id'), 'drafts', ['project_id'], unique=False)
    with op.batch_alter_table('drafts') as batch_op:
        batch_op.create_unique_constraint('uq_draft_project_version', ['project_id', 'version'])
    op.create_index(op.f('ix_evidence_cards_paper_id'), 'evidence_cards', ['paper_id'], unique=False)
    op.create_index(op.f('ix_evidence_cards_project_id'), 'evidence_cards', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_configs_is_active'), 'llm_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_paper_chunks_paper_id'), 'paper_chunks', ['paper_id'], unique=False)
    op.create_index(op.f('ix_papers_parse_status'), 'papers', ['parse_status'], unique=False)
    op.create_index(op.f('ix_papers_project_id'), 'papers', ['project_id'], unique=False)
    op.create_index(op.f('ix_papers_selected'), 'papers', ['selected'], unique=False)
    op.create_index(op.f('ix_review_issues_draft_id'), 'review_issues', ['draft_id'], unique=False)
    op.create_index(op.f('ix_review_issues_project_id'), 'review_issues', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_issues_project_id'), table_name='review_issues')
    op.drop_index(op.f('ix_review_issues_draft_id'), table_name='review_issues')
    op.drop_index(op.f('ix_papers_selected'), table_name='papers')
    op.drop_index(op.f('ix_papers_project_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_parse_status'), table_name='papers')
    op.drop_index(op.f('ix_paper_chunks_paper_id'), table_name='paper_chunks')
    op.drop_index(op.f('ix_llm_configs_is_active'), table_name='llm_configs')
    op.drop_index(op.f('ix_evidence_cards_project_id'), table_name='evidence_cards')
    op.drop_index(op.f('ix_evidence_cards_paper_id'), table_name='evidence_cards')
    with op.batch_alter_table('drafts') as batch_op:
        batch_op.drop_constraint('uq_draft_project_version', type_='unique')
    op.drop_index(op.f('ix_drafts_project_id'), table_name='drafts')
    # ### end Alembic commands ###
