"""add_strategy_fields_to_llm_config

Revision ID: 607cc55778da
Revises: 20260515_0001
Create Date: 2026-05-18 07:35:44.684202
"""

from alembic import op
import sqlalchemy as sa



revision = '607cc55778da'
down_revision = 'c133a708dc21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_configs') as batch_op:
        batch_op.add_column(sa.Column('strategy_mode', sa.String(length=16), server_default='balanced', nullable=False))
        batch_op.add_column(sa.Column('enable_reasoning', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('preferred_max_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'preferred_max_tokens')
    op.drop_column('llm_configs', 'enable_reasoning')
    op.drop_column('llm_configs', 'strategy_mode')
    # ### end Alembic commands ###
